version: 2.1
orbs: 
  node: circleci/node@5.0.0
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      -run:
        name: install-packages
        command: npm install & npm run build
workflows:
  version: 2
  build:
    jobs:
      - build